name: release
on:
  release:
    types: [created]
env:
  APP_NAME: nitter-rss-proxy
jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: [amd64, arm64,arm] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          goversion: https://dl.google.com/go/go1.20.linux-amd64.tar.gz
          ldflags: -s -w
          project_path: ./cmd
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: ${{ env.APP_NAME }} # 可以指定二进制文件的名称
